---
version: '2'
services:
  tunnel:
    image: camptocamp/ssh-tunnel:0.2.4
    ports:
      - '${SSH_PORT}:22'
    volumes:
      - 'sshconfig:/etc/ssh'
    environment:
      GITHUB_TOKEN: '${GITHUB_TOKEN}'
      GITHUB_ORG: '${GITHUB_ORG}'
      GITHUB_TEAM: '${GITHUB_TEAM}'
      GITHUB_USERS: '${GITHUB_USERS}'
      AUTHORIZED_KEYS: ${AUTHORIZED_KEYS}

volumes:
  sshconfig: {}
