---
version: '2'
.catalog:
  name: "SSH Tunnel"
  version: "v0.2.3-1"
  description: "SSH tunneling stack"
  uuid: ssh-tunnel-11
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "GITHUB_TOKEN"
      label: "Github Token"
      description: "Github authentication token"
      type: "string"
      required: false
    - variable: "GITHUB_ORG"
      label: "Github Organization"
      description: "Github Organization to allow"
      type: "string"
      required: false
    - variable: "GITHUB_TEAM"
      label: "Github Team"
      description: "Github Team to allow"
      type: "string"
      required: false
    - variable: "GITHUB_USERS"
      label: "Github Users"
      description: "Additional Github users to allow"
      type: "string"
      required: false
    - variable: "SSH_PORT"
      label: "SSH Port"
      description: "SSH Port to publish"
      type: "string"
      required: true
      default: "2222"
    - variable: "AUTHORIZED_KEYS"
      label: "Authorized keys"
      description: "Additional authorized keys"
      type: "multiline"
      required: false
